Student.create(first_name: "TestFirst1", last_name: "TestLast1")
Student.create(first_name: "TestFirst2", last_name: "TestLast2")
Student.create(first_name: "TestFirst2", last_name: "TestLast3")
SchoolClass.create(title: "TestClass1", room_number: 1)
SchoolClass.create(title: "TestClass2", room_number: 2)
SchoolClass.create(title: "TestClass3", room_number: 3)
